import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";
import { useState } from "react";
export default function Home({ data }) {
  {console.log('data :>> ', data)}
  const [clan,setClan]=useState(data.data);
  console.log('clan', clan.length)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner />
        {clan ? (
          <>
            <div className="centered">
              <div className="card w-96 bg-base-100 shadow-xl">
                <figure className="px-10 pt-10">
                  <img src={clan.badgeUrls.large} alt="Clan" className="rounded-xl" />
                </figure>
                <div className="card-body items-center text-center">
                  <h2 className="card-title">{clan.name}</h2>
                  <p>{clan.description}</p>
                </div>
              </div>
            </div>
            <div>
              <div className="overflow-x-auto p-5">
                <table className="table table-compact">
                  <thead>
                    <tr>
                      <th>S.No</th>
                      <th>Name</th>
                      <th>Details</th>
                      <th>Other Details</th>
                    </tr>
                  </thead>
                  <tbody>
                    {clan &&
                      clan.memberList.map((res) => (
                        <tr key={res.tag}>
                          <td>{res.clanRank}</td>
                          <td>
                            <div className="flex items-center space-x-3">
                              <div className="avatar">
                                <div className="mask mask-squircle w-12 h-12">
                                  <img src={res.league.iconUrls.medium} alt="Avatar " />
                                </div>
                              </div>
                              <div>
                                <div className="font-bold">{res.name}</div>
                                <div className="text-sm opacity-50">{res.role}</div>
                              </div>
                            </div>
                          </td>
                          <td>
                            <button className="btn gap-2">
                              Exp Level -<div className="badge"> {res.expLevel} </div>
                            </button>
                            <br />
                            <button className="btn gap-2">
                              Tropies
                              <div className="badge badge-info">{res.trophies}</div>
                            </button>
                            <button className="btn gap-2">
                              Versus Trophies
                              <div className="badge badge-success">{res.versusTrophies}</div>
                            </button>
                          </td>
                          <td>
                            <div className="badge badge-primary">
                              Donations:
                              {res.donations}
                            </div>
                            <div className="badge badge-accent">Donations Received : {res.donationsReceived}</div>
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </div>
            {/* <div className="centered p-5">
          {clan &&
            data.labels.map((res) => (
              <div className="card w-96 bg-base-100 shadow-xl image-full" key={res.name}>
                <figure>
                  <img src={res.iconUrls.medium} alt="Shoes" />
                </figure>
                <div className="card-body centered">
                  <h2 className="card-title">{res.name}</h2>
                </div>
              </div>
            ))}
        </div> */}
          </>
        ) : (
          <p>Token expired</p>
        )}

        <Footer />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(`https://coc-backend.onrender.com/data`);
  const data = await res.json();
  return { props: { data } };
}
